In [1]:
import pandas as pd
import numpy as mp

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import collections
from PIL import Image
#following imports are needed for ploting the tree
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

from matplotlib import pyplot as plt
import seaborn as sns
#Installing graphviz is a very hectic thing, go through some youtube tutorial for successfully installing graphvig and pydotplus
import graphviz
import pydotplus
import io
from scipy import misc
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

%matplotlib inline

In [2]:
class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [3]:
# data = pd.read_csv(r"bank.csv")
data = pd.read_csv(r"C:\Users\Hp\Desktop\ML\Classification\bank.csv")

In [4]:
data.head(3)

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes

In [5]:
data = MultiColumnLabelEncoder(columns = ['job','marital','education','default','housing','loan','contact','month','poutcome','deposit']).fit_transform(data)

In [6]:
features = data.columns
# display
features

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [7]:
#features = [x for x in features if x != 'deposit'] #This will take all the x or the inputs to the features without "deposit"
# display                                                   #because "deposit is Y or output"
features

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [8]:
features = [x for x in features if x != 'deposit']
features

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome']

In [9]:
dt = tree.DecisionTreeClassifier(min_samples_split = 100, criterion = 'entropy')

In [10]:
dt

DecisionTreeClassifier(criterion='entropy', min_samples_split=100)

In [11]:
train, test = train_test_split(data, test_size = 0.1)
print(len(data))
print(len(train))
print(len(test))

11162
10045
1117


In [12]:
x_train = train[features]
y_train = train["deposit"]

x_test = test[features]
y_test = test["deposit"]

In [13]:
# y_train = y_train.replace(to_replace=['no', 'yes'], value=[0, 1])
# y_test = y_test.replace(to_replace=['no', 'yes'], value=[0, 1])

In [14]:
dt = dt.fit(x_train, y_train)

In [15]:
y_pred = dt.predict(x_test)

In [16]:
#display
y_pred #These are the predicted values. 

array([1, 0, 1, ..., 0, 0, 0])

In [17]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred) * 100
print("Accuracy using desicion Tree: ", round(score, 1), "%" )

Accuracy using desicion Tree:  83.1 %


In [18]:
#Naive Bays

In [19]:
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

In [20]:
Nb=GaussianNB()
Nb= Nb.fit(x_train,y_train)

In [21]:
y_pred=Nb.predict(x_test)

In [22]:
#Diplay
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [23]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred) * 100
print("Accuracy using Naive Bayes: ", round(score, 1), "%" )

Accuracy using Naive Bayes:  74.7 %


In [24]:
#Nuoral Network

In [25]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [26]:

mlp = MLPClassifier(hidden_layer_sizes=(20,20,20), max_iter = 900, activation = 'relu')

In [28]:
x_train = train[features]
y_train = train["deposit"]

x_test = test[features]
y_test = test["deposit"]

In [29]:
mlp = mlp.fit(x_train, y_train)

In [30]:
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [31]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred) * 100
print("Accuracy using Neural Net: ", round(score, 1), "%" )

Accuracy using Neural Net:  74.7 %
